#include "llm/ops.h"
#include <cmath>
#include <algorithm>
#include <limits>
#include <stdexcept>
#include <string>
namespace llm { static void req(const Tensor&t,const char*n){if(t.device()!=DeviceType::CPU||t.dtype()!=DType::F32||!t.is_contiguous())throw std::runtime_error(std::string(n)+": requires contiguous CPU F32 tensor");} static void rank(const Tensor&t,size_t r,const char*n){if(t.shape().size()!=r)throw std::invalid_argument(std::string(n)+": expected rank "+std::to_string(r));}
Tensor embedding_lookup(const Tensor&w,const std::vector<int32_t>&ids){req(w,"embedding_lookup");rank(w,2,"embedding_lookup");auto s=w.shape();Tensor o(DType::F32,{(int64_t)ids.size(),s[1]});for(size_t i=0;i<ids.size();++i){if(ids[i]<0||ids[i]>=s[0])throw std::out_of_range("embedding_lookup: token id out of range");for(int64_t j=0;j<s[1];++j)o.set_f32(i*s[1]+j,w.get_f32(ids[i]*s[1]+j));}return o;}
Tensor linear(const Tensor&x,const Tensor&w){req(x,"linear");req(w,"linear");rank(x,2,"linear");rank(w,2,"linear");auto a=x.shape(),b=w.shape();if(a[1]!=b[1])throw std::invalid_argument("linear: feature shapes mismatch");Tensor o(DType::F32,{a[0],b[0]});for(int64_t i=0;i<a[0];++i)for(int64_t j=0;j<b[0];++j){float z=0;for(int64_t k=0;k<a[1];++k)z+=x.get_f32(i*a[1]+k)*w.get_f32(j*b[1]+k);o.set_f32(i*b[0]+j,z);}return o;}
Tensor rms_norm(const Tensor&x,const Tensor&w,float eps){req(x,"rms_norm");req(w,"rms_norm");rank(x,2,"rms_norm");rank(w,1,"rms_norm");auto s=x.shape();if(w.shape()[0]!=s[1])throw std::invalid_argument("rms_norm: hidden shape mismatch");Tensor o(DType::F32,s);for(int64_t i=0;i<s[0];++i){float q=0;for(int64_t j=0;j<s[1];++j){float v=x.get_f32(i*s[1]+j);q+=v*v;}float r=1/std::sqrt(q/s[1]+eps);for(int64_t j=0;j<s[1];++j)o.set_f32(i*s[1]+j,x.get_f32(i*s[1]+j)*r*w.get_f32(j));}return o;}
Tensor rope(const Tensor&x,const std::vector<int32_t>&p,float theta){req(x,"rope");rank(x,3,"rope");auto s=x.shape();if(s[2]%2)throw std::invalid_argument("rope: head_dim must be even");if(p.size()!=size_t(s[0]))throw std::invalid_argument("rope: position_ids length mismatch");if(theta<=0)throw std::invalid_argument("rope: theta must be positive");Tensor o(DType::F32,s);int64_t half=s[2]/2;for(int64_t t=0;t<s[0];++t)for(int64_t h=0;h<s[1];++h){size_t base=(t*s[1]+h)*s[2];for(int64_t i=0;i<half;++i){double f=double(p[t])*std::pow(double(theta),-2.0*double(i)/double(s[2]));float c=std::cos(f),si=std::sin(f),a=x.get_f32(base+i),b=x.get_f32(base+i+half);o.set_f32(base+i,a*c-b*si);o.set_f32(base+i+half,a*si+b*c);}}return o;}
Tensor causal_mask(size_t n){Tensor o(DType::F32,{(int64_t)n,(int64_t)n});for(size_t i=0;i<n;++i)for(size_t j=0;j<n;++j)o.set_f32(i*n+j,j<=i?0:-std::numeric_limits<float>::infinity());return o;}
Tensor softmax_last_dim(const Tensor&x){req(x,"softmax_last_dim");if(x.shape().empty())throw std::invalid_argument("softmax_last_dim: rank must be positive");auto s=x.shape();int64_t d=s.back();Tensor o(DType::F32,s);for(size_t base=0;base<x.numel();base+=d){float m=-std::numeric_limits<float>::infinity();for(int64_t j=0;j<d;++j)m=std::max(m,x.get_f32(base+j));float z=0;for(int64_t j=0;j<d;++j){float v=std::exp(x.get_f32(base+j)-m);o.set_f32(base+j,v);z+=v;}for(int64_t j=0;j<d;++j)o.set_f32(base+j,o.get_f32(base+j)/z);}return o;}
Tensor gqa_attention(const Tensor&q,const Tensor&k,const Tensor&v){req(q,"gqa_attention");req(k,"gqa_attention");req(v,"gqa_attention");rank(q,3,"gqa_attention");rank(k,3,"gqa_attention");rank(v,3,"gqa_attention");auto a=q.shape(),b=k.shape(),c=v.shape();if(a[0]<=0||a[1]<=0||a[2]<=0||b[1]<=0||b[2]<=0)throw std::invalid_argument("gqa_attention: T, heads and head_dim must be positive");if(a[0]!=b[0]||a[0]!=c[0]||a[2]!=b[2]||a[2]!=c[2]||b[1]!=c[1])throw std::invalid_argument("gqa_attention: incompatible sequence/head/head_dim shapes");if(a[1]%b[1]!=0)throw std::invalid_argument("gqa_attention: q_heads must be divisible by kv_heads");Tensor o(DType::F32,a);int64_t group=a[1]/b[1];double scale=1/std::sqrt(double(a[2]));for(int64_t t=0;t<a[0];++t)for(int64_t h=0;h<a[1];++h){int64_t kh=h/group;double max_score=-std::numeric_limits<double>::infinity();for(int64_t u=0;u<=t;++u){double score=0;for(int64_t e=0;e<a[2];++e)score+=double(q.get_f32((t*a[1]+h)*a[2]+e))*double(k.get_f32((u*b[1]+kh)*b[2]+e));max_score=std::max(max_score,score*scale);}double den=0;for(int64_t u=0;u<=t;++u){double score=0;for(int64_t e=0;e<a[2];++e)score+=double(q.get_f32((t*a[1]+h)*a[2]+e))*double(k.get_f32((u*b[1]+kh)*b[2]+e));den+=std::exp(score*scale-max_score);}for(int64_t d=0;d<a[2];++d){double z=0;for(int64_t u=0;u<=t;++u){double score=0;for(int64_t e=0;e<a[2];++e)score+=double(q.get_f32((t*a[1]+h)*a[2]+e))*double(k.get_f32((u*b[1]+kh)*b[2]+e));z+=std::exp(score*scale-max_score)*double(v.get_f32((u*c[1]+kh)*c[2]+d));}o.set_f32((t*a[1]+h)*a[2]+d,float(z/den));}}return o;}
Tensor swiglu(const Tensor&a,const Tensor&b){req(a,"swiglu");req(b,"swiglu");if(a.shape()!=b.shape())throw std::invalid_argument("swiglu: shape mismatch");Tensor o(DType::F32,a.shape());for(size_t i=0;i<a.numel();++i){float x=a.get_f32(i);o.set_f32(i,(x/(1+std::exp(-x)))*b.get_f32(i));}return o;}
Tensor add(const Tensor&a,const Tensor&b){req(a,"add");req(b,"add");if(a.shape()!=b.shape())throw std::invalid_argument("add: shape mismatch");Tensor o(DType::F32,a.shape());for(size_t i=0;i<a.numel();++i)o.set_f32(i,a.get_f32(i)+b.get_f32(i));return o;}
Tensor lm_head(const Tensor&h,const Tensor&w){return linear(h,w);}
}
