#!/usr/bin/env python3
import argparse, hashlib, json, shutil, sys
from pathlib import Path

MODEL_ID="Qwen/Qwen3-0.6B"; LAYERS=28
def expected_shape(logical):
    if logical == "token_embedding": return [151936, 1024]
    if logical == "final_norm": return [1024]
    if not logical.startswith("layers."): raise KeyError(logical)
    parts=logical.split(".")
    if len(parts)!=3 or not parts[1].isdigit() or not 0<=int(parts[1])<LAYERS: raise KeyError(logical)
    return {"input_norm":[1024],"q_proj":[2048,1024],"k_proj":[1024,1024],"v_proj":[1024,1024],"q_norm":[128],"k_norm":[128],"o_proj":[1024,2048],"post_attention_norm":[1024],"gate_proj":[3072,1024],"up_proj":[3072,1024],"down_proj":[1024,3072]}[parts[2]]
def expected_shapes():
    out={"token_embedding":expected_shape("token_embedding"),"final_norm":expected_shape("final_norm")}
    for i in range(LAYERS):
        for n in ("input_norm","q_proj","k_proj","v_proj","q_norm","k_norm","o_proj","post_attention_norm","gate_proj","up_proj","down_proj"): out[f"layers.{i}.{n}"]=expected_shape(f"layers.{i}.{n}")
    return out
def validate_shape(logical, source, actual):
    expected=expected_shape(logical); actual=list(map(int,actual))
    if actual!=expected: raise ValueError(f"shape mismatch logical tensor {logical}, Hugging Face source tensor {source}, actual shape {actual}, expected shape {expected}")
def blocker(s): print("BLOCKER: "+s,file=sys.stderr); raise SystemExit(2)
def fnv(data):
    h=1469598103934665603
    for x in data: h=((h^x)*1099511628211)&0xffffffffffffffff
    return h
def main():
    ap=argparse.ArgumentParser();ap.add_argument("--model-id",default=MODEL_ID);ap.add_argument("--output-dir",default="artifacts/phase15/qwen3-0.6b-f32");a=ap.parse_args()
    try:
        import torch
        from safetensors import safe_open
        from transformers import AutoConfig, AutoTokenizer
    except Exception as e: blocker("converter requires torch, safetensors and transformers: "+repr(e))
    try: cfg=AutoConfig.from_pretrained(a.model_id,local_files_only=True)
    except Exception as e: blocker("local model config unavailable: "+repr(e))
    theta=getattr(cfg,"rope_theta",None) or cfg.rope_parameters["rope_theta"]
    expected={"hidden_size":1024,"num_hidden_layers":28,"num_attention_heads":16,"num_key_value_heads":8,"head_dim":128,"intermediate_size":3072,"vocab_size":151936,"rms_norm_eps":1e-6,"rope_theta":1000000,"tie_word_embeddings":True}
    got={"hidden_size":cfg.hidden_size,"num_hidden_layers":cfg.num_hidden_layers,"num_attention_heads":cfg.num_attention_heads,"num_key_value_heads":cfg.num_key_value_heads,"head_dim":cfg.head_dim,"intermediate_size":cfg.intermediate_size,"vocab_size":cfg.vocab_size,"rms_norm_eps":cfg.rms_norm_eps,"rope_theta":theta,"tie_word_embeddings":cfg.tie_word_embeddings}
    for k,v in expected.items():
        if got[k]!=v: blocker(f"config mismatch {k}: got {got[k]!r}, expected {v!r}")
    snap=Path(cfg._name_or_path) if Path(str(cfg._name_or_path)).is_dir() else None
    try: snap=Path(__import__("huggingface_hub").snapshot_download(a.model_id,local_files_only=True))
    except Exception as e: blocker("local Hugging Face snapshot unavailable: "+repr(e))
    sf=next(snap.glob("*.safetensors"),None)
    if sf is None: blocker("no local safetensors file in snapshot "+str(snap))
    out=Path(a.output_dir); marker=out/".cuda_llm_package_v1"
    if out.exists() and any(x.name!=marker.name for x in out.iterdir()) and not marker.exists(): blocker("refusing to overwrite non-empty unmarked output directory: "+str(out))
    out.mkdir(parents=True,exist_ok=True); marker.write_text("generated by convert_qwen3_hf.py\n"); (out/"tokenizer").mkdir(exist_ok=True)
    tok=AutoTokenizer.from_pretrained(a.model_id,local_files_only=True)
    for n in ("tokenizer.json","tokenizer_config.json","generation_config.json"):
        src=snap/n
        if not src.exists(): blocker("tokenizer artifact missing: "+str(src))
        shutil.copy2(src,out/"tokenizer"/n)
    messages=[{"role":"system","content":"You are a helpful assistant."},{"role":"user","content":"Explain why key-value caching improves autoregressive transformer decoding."}]
    plain="Explain why key-value caching improves autoregressive transformer decoding."
    def fixture(text,chat=False):
        rendered=tok.apply_chat_template(text,tokenize=False,add_generation_prompt=True) if chat else text
        ids=tok.encode(rendered,add_special_tokens=not chat)
        return {"rendered_prompt":rendered,"token_ids":ids,"bos_token_id":tok.bos_token_id,"eos_token_id":tok.eos_token_id,"special_token_ids":{k:v for k,v in {"bos":tok.bos_token_id,"eos":tok.eos_token_id,"pad":tok.pad_token_id}.items() if v is not None}}
    (out/"tokenizer_fixtures.json").write_text(json.dumps({"model_id":a.model_id,"plain_text":plain,"fixtures":[{"kind":"plain",**fixture(plain)},{"kind":"chat","messages":messages,**fixture(messages,True)}]},ensure_ascii=False,indent=2)+"\n")
    required={"token_embedding":"model.embed_tokens.weight","final_norm":"model.norm.weight"}
    for i in range(LAYERS):
        p=f"layers.{i}."; q=f"model.layers.{i}."; required.update({p+"input_norm":q+"input_layernorm.weight",p+"q_proj":q+"self_attn.q_proj.weight",p+"k_proj":q+"self_attn.k_proj.weight",p+"v_proj":q+"self_attn.v_proj.weight",p+"q_norm":q+"self_attn.q_norm.weight",p+"k_norm":q+"self_attn.k_norm.weight",p+"o_proj":q+"self_attn.o_proj.weight",p+"post_attention_norm":q+"post_attention_layernorm.weight",p+"gate_proj":q+"mlp.gate_proj.weight",p+"up_proj":q+"mlp.up_proj.weight",p+"down_proj":q+"mlp.down_proj.weight"})
    with safe_open(str(sf),framework="pt",device="cpu") as f: keys=set(f.keys())
    for logical,key in required.items():
        if key not in keys: blocker("missing weight "+key)
    # Read and validate every source shape before creating/truncating weights.bin.
    with safe_open(str(sf),framework="pt",device="cpu") as f:
        for logical,key in required.items():
            try: validate_shape(logical,key,f.get_tensor(key).shape)
            except ValueError as e: blocker(str(e))
    meta=[]; report=[]; offset=0; physical=0
    with safe_open(str(sf),framework="pt",device="cpu") as f, open(out/"weights.bin","wb") as wf:
        for logical,key in required.items():
            offset=(offset+63)//64*64
            wf.write(b"\0"*(offset-wf.tell()))
            t=f.get_tensor(key).detach().float().contiguous(); data=t.numpy().tobytes(order="C"); wf.write(data); h=fnv(data); shape=" ".join(map(str,t.shape)); meta.append(f"tensor {logical} f32 {t.ndim} {shape} {offset} {len(data)} {h:016x}"); report.append(f"{logical} shape={list(t.shape)} offset={offset} byte_size={len(data)} fnv1a64={h:016x}");offset+=len(data);physical+=1
    meta.append("alias lm_head token_embedding")
    (out/"model.meta").write_text("\n".join(["format cuda_llm_model_package_v1","model_type qwen3",f"source_model {a.model_id}","source_dtype bfloat16","export_dtype f32","hidden_size 1024","num_hidden_layers 28","num_attention_heads 16","num_key_value_heads 8","head_dim 128","intermediate_size 3072","vocab_size 151936","rms_norm_eps 1e-6","rope_theta 1000000","tie_word_embeddings true"]+meta)+"\n")
    sha=hashlib.sha256(sf.read_bytes()).hexdigest(); (out/"conversion_report.txt").write_text(f"source_snapshot {snap}\nsource_file {sf.name}\nsource_sha256 {sha}\nphysical_tensor_count {physical}\nalias_count 1\nweights_bin_bytes {offset}\n"+"\n".join(report)+"\n")
    print("converted",physical,"physical tensors to",out)
if __name__=="__main__":main()
