#include "llm/model_package.h"
#include "llm/qwen3_layer.h"
#include <algorithm>
#include <cmath>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <map>
#include <sstream>
#include <stdexcept>
#include <string>
#include <vector>
using namespace llm; namespace fs=std::filesystem;
static void fail(const std::string&s){throw std::runtime_error("test_model_package: "+s);}
struct E{std::string file;std::vector<int64_t> shape;};
static std::map<std::string,E> mf(const fs::path&p){std::ifstream in(p);if(!in)fail("missing golden manifest");std::map<std::string,E>r;std::string n,f;int rank;while(in>>n>>f>>rank){E e{f,{}};for(int i=0;i<rank;++i){int64_t d;if(!(in>>d))fail("bad manifest");e.shape.push_back(d);}r[n]=e;}return r;}
static Tensor file(const fs::path&d,const std::map<std::string,E>&m,const std::string&n){auto i=m.find(n);if(i==m.end())fail("golden node missing "+n);std::ifstream in(d/i->second.file,std::ios::binary|std::ios::ate);if(!in)fail("golden file missing "+n);auto sz=static_cast<size_t>(in.tellg());size_t num=1;for(auto x:i->second.shape)num*=size_t(x);if(sz!=num*4)fail("golden byte size "+n);in.seekg(0);std::vector<float>v(num);in.read(reinterpret_cast<char*>(v.data()),sz);return Tensor::from_f32(i->second.shape,v);}
static double cos(const Tensor&a,const Tensor&b){double ab=0,aa=0,bb=0;for(size_t i=0;i<a.numel();++i){double x=a.get_f32(i),y=b.get_f32(i);ab+=x*y;aa+=x*x;bb+=y*y;}return aa&&bb?ab/std::sqrt(aa*bb):aa==bb?1:0;}
static void cmp(const std::string&n,const Tensor&a,const Tensor&b){if(a.shape()!=b.shape())fail(n+" shape mismatch");float mx=0;double mean=0;for(size_t i=0;i<a.numel();++i){float d=std::fabs(a.get_f32(i)-b.get_f32(i));mx=std::max(mx,d);mean+=d;}mean/=a.numel();double c=cos(a,b);std::cout<<n<<" shape=";for(auto d:a.shape())std::cout<<d<<"x";std::cout<<" max_abs_error="<<mx<<" mean_abs_error="<<mean<<" cosine_similarity="<<c<<"\n";if(mx>5e-4||c<.99999)fail(n+" threshold max_error="+std::to_string(mx)+" cosine_similarity="+std::to_string(c));}
static Tensor z(std::vector<int64_t>s){size_t n=1;for(auto d:s)n*=size_t(d);return Tensor::from_f32(s,std::vector<float>(n));}
static double package_positive(const ModelPackage&p,const std::string&key){const std::string v=p.config(key);size_t pos=0;double x;try{x=std::stod(v,&pos);}catch(...){fail("config "+key+" is not a valid number: "+v);}if(pos!=v.size()||!std::isfinite(x)||x<=0)fail("config "+key+" invalid actual="+v);return x;}
int main(){try{
 fs::path pkg="artifacts/phase15/qwen3-0.6b-f32",gold="artifacts/phase1/qwen3_layer0";if(!fs::exists(pkg/"model.meta"))pkg="../"+pkg.string();if(!fs::exists(gold/"manifest.txt"))gold="../"+gold.string();if(!fs::exists(pkg/"model.meta")||!fs::exists(gold/"manifest.txt"))fail("package or Phase 1 fixture missing");
 ModelPackage p(pkg);if(p.resolve_name("lm_head")!="token_embedding")fail("lm_head alias does not resolve to token_embedding");if(p.tensors().size()!=310||p.aliases().size()!=1)fail("unexpected physical tensor/alias count");std::map<std::string,bool> present;for(auto&t:p.tensors())present[t.name]=true;for(int i=0;i<28;++i)for(auto n:{"input_norm","q_proj","k_proj","v_proj","q_norm","k_norm","o_proj","post_attention_norm","gate_proj","up_proj","down_proj"})if(!present["layers."+std::to_string(i)+"."+n])fail("missing layer weight");
 auto gm=mf(gold/"manifest.txt");auto h=file(gold,gm,"hidden_states"),pos=file(gold,gm,"position_ids");std::vector<int32_t> ids(pos.numel());for(size_t i=0;i<ids.size();++i)ids[i]=int32_t(pos.get_f32(i));double eps=package_positive(p,"rms_norm_eps"),theta=package_positive(p,"rope_theta");std::cout<<"rms_norm_eps="<<eps<<" rope_theta="<<theta<<"\n";Qwen3LayerWeights w{p.load_tensor("layers.0.input_norm"),p.load_tensor("layers.0.q_proj"),p.load_tensor("layers.0.k_proj"),p.load_tensor("layers.0.v_proj"),p.load_tensor("layers.0.q_norm"),p.load_tensor("layers.0.k_norm"),p.load_tensor("layers.0.o_proj"),p.load_tensor("layers.0.post_attention_norm"),p.load_tensor("layers.0.gate_proj"),p.load_tensor("layers.0.up_proj"),p.load_tensor("layers.0.down_proj")};auto r=qwen3_decoder_layer_trace(h,ids,w,float(eps),float(theta));for(auto&x:std::map<std::string,const Tensor*>{{"q_linear",&r.q_linear},{"q_rope",&r.q_rope},{"attention_output",&r.attention_output},{"swiglu_output",&r.swiglu_output},{"layer_output",&r.layer_output}})cmp(x.first,*x.second,file(gold,gm,x.first));
 fs::path tmp=fs::temp_directory_path()/"cuda_llm_package_meta_test";fs::remove_all(tmp);fs::create_directories(tmp);fs::copy_file(pkg/"model.meta",tmp/"model.meta");fs::create_symlink(pkg/"weights.bin",tmp/"weights.bin");bool rejected=false;{std::ifstream in(tmp/"model.meta");std::string all((std::istreambuf_iterator<char>(in)),{});auto at=all.find("tensor token_embedding");auto hex=all.find_last_of(' ',all.find('\n',at)-1);all.replace(hex+1,16,"0000000000000000");std::ofstream out(tmp/"model.meta");out<<all;}try{ModelPackage bad(tmp);bad.load_tensor("token_embedding");}catch(...){rejected=true;}if(!rejected)fail("checksum corruption was accepted");{std::ifstream in(pkg/"model.meta");std::string all((std::istreambuf_iterator<char>(in)),{});auto at=all.find("rope_theta 1000000");all.replace(at,std::string("rope_theta 1000000").size(),"rope_theta 42");std::ofstream out(tmp/"model.meta");out<<all;}rejected=false;try{ModelPackage bad(tmp);}catch(...){rejected=true;}if(!rejected)fail("invalid rope_theta was accepted");{std::ifstream in(pkg/"model.meta");std::string all((std::istreambuf_iterator<char>(in)),{});auto at=all.find("num_hidden_layers 28\n");all.erase(at,std::string("num_hidden_layers 28\n").size());std::ofstream out(tmp/"model.meta");out<<all;}rejected=false;try{ModelPackage bad(tmp);}catch(...){rejected=true;}if(!rejected)fail("missing required config was accepted");{std::ifstream in(pkg/"model.meta");std::string all((std::istreambuf_iterator<char>(in)),{});std::ofstream out(tmp/"model.meta");out<<all<<"alias invalid missing_target\n";}rejected=false;try{ModelPackage bad(tmp);}catch(...){rejected=true;}if(!rejected)fail("invalid alias was accepted");fs::remove_all(tmp);return 0;
 }catch(const std::exception&e){std::cerr<<e.what()<<"\n";return 1;}}
